name: 'OpenY Multilanguage Settings'
description: 'Settings for multi language site'
type: module
core: 8.x
dependencies:
  - config_translation
  - content_moderation
  - content_translation
  - file
  - groupex_form_cache
  - language
  - locale
  - menu_link_content
  - openy_session_instance
  - redirect
  - user
version: 8.x-1.0
